#spring:
#  application:
#    name: gateway
#  config:
#    import: optional:configserver:http://localhost:8888
eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  application:
    name: gateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: client-service
          uri: http://localhost:8099
          predicates:
            - Path=/api/client/**
        - id: finance-service
          uri: http://localhost:8070
          predicates:
            - Path=/api/finance/**