eureka:
  client:
    register-with-eureka: false

server:
  port: 8222

spring:
  application:
    name: gateway
  config:
    import: optional:configserver:http://localhost:8888

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: client-service
          uri: http://localhost:8099
          predicates:
            - Path=/api/client/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
        - id: finance-service
          uri: http://localhost:8070
          predicates:
            - Path=/api/finance/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
        - id: employees-service
          uri: http://localhost:8088
          predicates:
            - Path=/api/employees/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
        - id: demandes-credit-service
          uri: http://localhost:9898
          predicates:
            - Path=/api/loan-applications/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
        - id: flask-microservice
          uri: http://127.0.0.1:5000
          predicates:
            - Path=/api/prediction/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
        - id: email-service
          uri: http://localhost:9099
          predicates:
            - Path=/api/notifications/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE