eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: client-service
          uri: http://client-service:8080
          predicates:
            - Path=/api/client/**
        - id: finance-service
          uri: http://client-service:8080
          predicates:
            - Path=/api/finance/**

#management:
#  tracing:
#    sampling:
#      probability: 1.0
