eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false # Désactive l'enregistrement auprès de lui-même
    fetch-registry: false       # Empêche de récupérer la liste des instances (utile pour Eureka Server)
    service-url:
      defaultZone:  http://eureka-server:8761/eureka
server:
  port: 8761
spring:
  config:
    import: optional:configserver:http://config-server:8888
