eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone:  http://eureka-server:8761/eureka
    register-with-eureka: true
    fetch-registry: true
spring:
  application:
    name: credit-simulator-service
  config:
    import: optional:configserver:http://localhost:8888

